::: {.content-visible when-profile="english"}
# Leadership and appointments

## ESC
- Alumni Task Force Member, European Heart Academy \hfill 2025-2026

## SCMR
- Editor, Journal Watch column (monthly newsletter «SCMR NewsBeat») \hfill 2024-present
- Member, Science Committee \hfill 2025-2026
- Member, Education & COI Mitigation Committee \hfill 2025-2026
- Oral Abstract Moderator, SCMR 2025, Washington, USA \hfill January 2025

## EACVI
- Member, Web & Communication Committee \hfill 2025-2026

## Other appointments
- Abstract reviewer, ACC.25, Chicago, USA \hfill November 2024
- Continued scientific peer review activity, including  for the following journals since 2020: *European Heart Journal*, *The International Journal of Cardiovascular Imaging*, *Open Heart*.

:::
::: {.content-visible when-profile="italian"}
# Leadership e incarichi

## ESC
- Membro della Alumni Task Force, European Heart Academy \hfill 2025-2026

## SCMR
- Editor, rubrica *SCMR Journal Watch* (newsletter mensile SCMR NewsBeat) \hfill 2024-presente
- Membro, Science Committee \hfill 2025-2026
- Membro, Education & COI Mitigation Committee \hfill 2025-2026
- Moderatore di sessioni orali, SCMR 2025, Washington, Stati Uniti \hfill Gennaio 2025

## EACVI
- Membro, Web & Communication Committee \hfill 2025-2026

## Altri incarichi
- Revisore di abstract, ACC.25, Chicago, Stati Uniti \hfill Novembre 2024
- Attività di revisione paritaria per le seguenti riviste indicizzate: *European Heart Journal*, *The International Journal of Cardiovascular Imaging*, *Open Heart*, *Journal of Clinical Medicine*, *Frontiers in Public Health*, *Medicina*, *Children*
:::