
::: {.content-visible when-profile="english"}
# Conference presentations
:::

::: {.content-visible when-profile="italian"}
# Presentazioni a congressi internazionali
:::

## European Society of Cardiology

*Non-invasive imaging to guide percutaneous coronary revascularization in chronic total occlusion: a systematic review and meta-analysis*.
Presenting author: **G. Bisaccia**. [ESC Congress, London, UK (August 2024)]{.content-visible when-profile="english"} [ESC Congress, Londra, Regno Unito (Agosto 2024)]{.content-visible when-profile="italian"}

*Prognostic yield of stress CMR to evaluate chronic coronary syndromes: a systematic review and meta-analysis*.
Presenting author: **G. Bisaccia**. [ESC Congress, Barcelona, Spain (August 2022)]{.content-visible when-profile="english"} [ESC Congress, Barcellona, Spagna (Agosto 2022)]{.content-visible when-profile="italian"}

*Diagnostic accuracy of stress CMR to evaluate chronic coronary syndromes: an updated meta-analysis*.
Presenting author: **G. Bisaccia**. [ESC Congress, Barcelona, Spain (August 2022)]{.content-visible when-profile="english"} [ESC Congress, Barcellona, Spagna (Agosto 2022)]{.content-visible when-profile="italian"}

*Cardiovascular morbidity and mortality related to non-alcoholic fatty liver disease: a systematic review and meta-analysis of prospective studies*.
Presenting author: **G. Bisaccia**. [ESC Congress (The Digital Experience) (August 2021)]{.content-visible when-profile="english"} [ESC Congress (The Digital Experience) (Agosto 2021)]{.content-visible when-profile="italian"}

## American Heart Association

*Comparative and Incremental Diagnostic and Prognostic Yield of Exercise ECG, CMR and SPECT in Patients With Suspected Ischaemic Heart Disease: A CE-MARC Sub-Study*.
Presenting author: **G. Bisaccia**. [AHA Scientific Sessions, Philadelphia, USA (Nov 2023)]{.content-visible when-profile="english"} [AHA Scientific Sessions, Philadelphia, USA (Novembre 2023)]{.content-visible when-profile="italian"}

## European Association of Cardiovascular Imaging

*CMR reclassifies patients with suspected myocardial infarction with non-obstructive coronary arteries (MINOCA)*.
Presenting author: **G. Bisaccia**. [EACVI, Barcelona, Spain (May 2023)]{.content-visible when-profile="english"} [EACVI, Barcellona, Spagna (Maggio 2023)]{.content-visible when-profile="italian"}

## Society for Cardiovascular Magnetic Resonance 
*Impact of Age and Sex on Myocardial Involvement in hospitalized COVID-19 patients: A Pre-specified Subanalysis of COVID-HEART*. Presenting author: **G. Bisaccia**. [SCMR Scientific Sessions 2025 in Washington, US (Jan 2025).]{.content-visible when-profile="english"} [SCMR Scientific Sessions 2025 a Washington, Stati Uniti (Gennaio 2025).]{.content-visible when-profile="italian"}

[*Early Career Award* finalist]{.content-visible when-profile="english"} [Finalista *Early Career Award*]{.content-visible when-profile="italian"} - *CMR as the First Line Test Compared to Exercise ECG and SPECT in Patients with Stable Chest Pain: Insights from CE-MARC*. Presenting author: **G. Bisaccia**. [CMR 2024, London, UK (Jan 2024)]{.content-visible when-profile="english"}[CMR 2024 (Gennaio 2024)]{.content-visible when-profile="italian"}.

*Prognostic Value of Myocardial Blood Flow Index Among Heart Transplant Recipients*.
Presenting author: **G. Bisaccia**. [CMR 2024, London, UK (Jan 2024).]{.content-visible when-profile="english"} [CMR 2024 (Gennaio 2024).]{.content-visible when-profile="italian"}

*Safety and Feasibility of Adenosine Stress CMR for CAV Detection in Orthotopic Heart Transplant Recipients*.
Presenting author: **G. Bisaccia**. [CMR 2024 London, UK (Jan 2024).]{.content-visible when-profile="english"} [CMR 2024 (Gennaio 2024).]{.content-visible when-profile="italian"}

*Diagnostic and Prognostic Value of Stress CMR Imaging to Evaluate Stable Chest Pain: A Twenty-Year Meta-Analysis*. Presenting author: **G. Bisaccia**. [SCMR 2023 San Diego, US (Jan 2023).]{.content-visible when-profile="english"} [SCMR 2023 San Diego, Stati Uniti (Gennaio 2023).]{.content-visible when-profile="italian"}

## British Society of Cardiovascular Magnetic Resonance 
[*Young Investigator Award* finalist]{.content-visible when-profile="english"} [Finalista *Young Investigator Award*]{.content-visible when-profile="italian"} - *How late is too late? Influence of scan timing on CMR’s diagnostic yield in suspected MINOCA*. Presenting author: **G. Bisaccia**. [BSCMR Annual Conference 2025, London, UK (Mar 2025)]{.content-visible when-profile="english"} [BSCMR 2025 (Marzo 2025)]{.content-visible when-profile="italian"}.

::: {.content-visible when-profile="english"}
## Other invited presentations
:::

::: {.content-visible when-profile="italian"}
# Altre presentazioni su invito
:::

*Cardiac MRI in suspected myocardial infarction with nonobstructive coronary artery disease*. Curso Imágenes Cardíacas, Universidad San Sebastián and Clinica Sanatorio Alemán, Concepción, [Chile (May 2025)]{.content-visible when-profile="english"}[Cile (Maggio 2025)]{.content-visible when-profile="italian"}.

*Safety and feasibility of adenosine stress cardiac MRI in heart transplant recipients*. [Italian Society of Cardiology CMR Journal Club, online (April 2025)]{.content-visible when-profile="english"} [Journal Club online organizzato dal Gruppo di Studio Risonanza Magnetica Cardiaca della Società Italiana di Cardiologia (Aprile 2025).]{.content-visible when-profile="italian"}. 