project:
  type: website
  output-dir: docs

profile:
  default: english
  group: 
    - [english, italian]

website:
  title: "G. Bisaccia, MD, PhD"
  
  navbar:
    logo: images/profile.jpg
    left:
      - icon: file-earmark-text
        text: CV
        href: index.qmd
    right:
      - text: Portfolio website
        href: https://bisacciamd.com
  page-footer: "Developed with Quarto by Giandomenico Bisaccia — 2024" 
  reader-mode: false
format:
  html:
    theme: 
      light: [litera, styles.scss]
      dark: [superhero, styles.scss]
    css: styles.css
    toc: true
    toc-location: left
#  docx:
#    reference-doc: custom-reference-doc.docx
csl: jacc-cvi.csl
execute: 
  freeze: false
