::: {.content-visible when-profile="english"}
# Teaching and consultancy

## *London School of Economics & Political Science, London, UK* 

### Consultant, LSE Health \hfill 2025-present
- Economic evaluation of cardiovascular disease interventions

## *University of Padua, Italy* 

### Lecturer, MSc in Cardiovascular Magnetic Resonance \hfill 2025-present
-  Course convenor: Prof. M. Perazzolo Marra
  - "Principal investigation protocols in CMR" \hfill 2025
  - "CMR safety" \hfill 2024-2025

## *G. d’Annunzio University of Chieti and Pescara, Chieti, Italy*
### Lecturer, MSc in Cardiovascular Magnetic Resonance \hfill 2025-present
- Undergraduate radiographer course \hfill 2024-2025

:::

::: {.content-visible when-profile="italian"}
# Insegnamento e consulenza

## *London School of Economics & Political Science, London, UK* 

### Consulente esterno, LSE Health \hfill 2025-presente
- Valutazione economica di interventi sanitari in cardiologia 

## *Università di Padova, Italia* 

### Docente, Master di II livello "Risonanza magnetica cardiaca" \hfill 2025-presente
- Direzione: Prof.ssa M. Perazzolo Marra
  - "Principal investigation protocols in CMR" \hfill 2025
  -  "CMR safety" \hfill 2024-2025

## *Università G. d'Annunzio di Chieti e Pescara, Chieti, Italia* 

### Cultore della materia, Corso di Laurea in Tecniche di Radiologia Medica  \hfill 2024-presente
- Attività didattica opzionale "Applicazioni cliniche della RM cardiaca"

:::