---
#title: Giandomenico Bisaccia
format:
  html: default
  quarto-cv-pdf: 
    hyperrefoptions: draft
author: Giandomenico Bisaccia, MD, PhD
date: last-modified
#jobtitle: Early career medical researcher
email: bisacciagiandomenico@gmail.com
#phone: '+39 350 533 1123'
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
orcid: 0000-0003-4606-3093 # orcid identifier
linkedin: bisacciamd
#twitter: twitter # twitter handle
web: 'bisacciamd.com'
fontawesome: yes
nocite: '@*'
validate-yaml: false
csl: apa-cv.csl
---

::: {.content-visible when-profile="english"}
# Experience

*G. d’Annunzio University of Chieti and Pescara, Chieti, Italy* \hfill May 2024-present

- Research fellow in cardiology
  - Supervised clinical research with focus on clinical applications of cardiovascular magnetic resonance imaging (CMR)
  - Coordination of undergraduate and postgraduate students

*Royal Brompton Hospital, London, UK* \hfill May 2023—present

- Honorary clinical research fellowship (part-time)
   - Supervised clinical research on quantitative stress perfusion CMR, ischaemic and nonischaemic cardiomyopathies, CMR guidance to percutaneous revascularization

*Harefield Hospital, London, UK* \hfill Sept 2022—May 2023

- Honorary clinical research fellowship (full time)
  - Prepared initial reports for 300+ clinical CMR scans
  - Conducted an audit on stress CMR after heart transplantation
  - Researched on CMR in patients with angina, cardiomyopathies, and after heart transplantation
  - Improved team productivity with data science and coding skills
:::

::: {.content-visible when-profile="italian"}
# Esperienza

*Università G. d’Annunzio di Chieti e Pescara, Chieti, Italia* \hfill Maggio 2024-presente

- Assegnista di ricerca in malattie dell'apparato cardiovascolare (SSD MED/11)
  - Linee di ricerca: risonanza magnetica cardiaca (CMR) da stress, cardiomiopatie ischemiche e nonischemiche
  - Supervisione e coordinamento di tesisti e medici in formazione

*Royal Brompton Hospital, Londra, Regno Unito* \hfill Mag 2023—presente

- Honorary clinical research fellowship (part-time)
   - Linee di ricerca: stress CMR, rivascolarizzazione miocardica percutanea

*Harefield Hospital, Londra, Regno Unito* \hfill Settembre 2022—Mag 2023

- Honorary clinical research fellowship (a tempo pieno)
  - Preparazione di 300+ report preliminari di studi clinici di CMR
  - Conduzione di un audit clinico sul profilo di *safety* e *feasibility* della stress CMR nei pazienti con pregresso trapianto cardiaco
  - Attività di ricerca: utilità clinica della CMR in pazienti con dolore toracico e cardiomiopatie

:::

::: {.content-visible when-profile="english"}

# Education

*London School of Economics, London, UK* \hfill Dec 2023—Dec 2025

- MSc in Health Economics, Outcomes and Management in Clinical Sciences (class of 2025)
  - Taught modules included Economic Analysis for Health Policy (distinction), Quality and Outcomes in Clinical Sciences (distinction), Economic Evaluation in Health Care, and Fundamentals of Management and Leadership (under assessment)
  - Volunteered as the class Clinical Student Representative for 2023/24

*G. d’Annunzio University of Chieti and Pescara, Chieti, Italy*

- PhD (*Doctor Europaeus*) in Neuroscience and Imaging (marked: excellent) \hfill Oct 2021—Mar 2024
   - Thesis title: *Value of Quantitative Stress Perfusion CMR in the Long-Term Assessment of Cardiac Transplantation Recipients* 
   - Supervised by Prof. S. Gallina and F. Ricci (Italy) and Prof. C. Bucciarelli-Ducci (UK), external assessment by Prof. A. Almeida (Portugal) and Prof. J. Garot (France), external examination by Prof. R. Manka (Switzerland) 
   - Co-authored 17 peer-reviewed publications
   - Supervised 12 undergraduate and 4 postgraduate students
   - Presented research findings for 7 original research studies at major international conferences

- Master's Degree in Medicine (summa cum laude) \hfill Oct 2014—Apr 2021 
    - Thesis title: *CMR Reference Values of Mitral and Tricuspid Annular Dimensions: the UK BioBank Cohort* 
    - MD-PhD research track \hfill Nov 2019-Ott 2020
    - Path of Excellence research track \hfill Ott 2016—Ott 2019
:::

::: {.content-visible when-profile="italian"}

# Istruzione

*London School of Economics, Londra, Regno Unito* \hfill Dicembre 2023—Dicembre 2025

- MSc in Health Economics, Outcomes and Management in Clinical Sciences (classe del 2025)
  - Corsi frequentati: Economic Analysis for Health Policy (distinction), Quality and Outcomes in Clinical Sciences (distinction), Economic Evaluation in Health Care, e Fundamentals of Management and Leadership (valutazione in corso)
  - Rappresentante di classe volontario per l'anno accademico 2023/24

*Università G. d'Annunzio di Chieti e Pescara, Chieti, Italia*

- Dottorato in Neuroscienze e Imaging (Doctor Europaeus, SSD: MED/11) \hfill Ottobre 2021—Marzo 2024

   Tesi: *Value of Quantitative Stress Perfusion CMR in the Long-Term Assessment of Cardiac Transplantation Recipients*
   
   Qualifica aggiuntiva: *Doctor Europaeus* (internazionalità del progetto, dei supervisori e dei revisori; tesi discussa in lingua inglese)

   - Autore di 17 pubblicazioni peer-reviewed
   - Correlatore di 12 laureandi e 4 medici in formazione specialistica
   
- Laurea magistrale in Medicina e Chirurgia (LM-41, 110 e lode) \hfill Ottobre 2014—Aprile 2021
  
  - Tesi: *CMR Reference Values of Mitral and Tricuspid Annular Dimensions: the UK BioBank Cohort* (SSD MED/11)
  - Percorso MD-PhD di ricerca clinica \hfill Nov 2019-Ott 2020
  - Percorso di Eccellenza in Medicina \hfill Ott 2016—Ott 2019

:::

\newpage

::: {.content-visible when-profile="english"}
# Teaching
*G. d’Annunzio University of Chieti and Pescara, Chieti, Italy*

- Honorary teaching assistant in clinical applications of CMR, Undergraduate radiographer course \hfill May 2024

*University of Padua, Italy* 

- Lecturer on CMR safety, MSc in Cardiac magnetic resonance imaging\hfill Jan 2024
:::

::: {.content-visible when-profile="italian"}
# Attività di insegnamento
*Università G. d'Annunzio di Chieti e Pescara, Chieti, Italia* \hfill Maggio 2024

- Cultore della materia, Attività didattica opzionale "Applicazioni cliniche della risonanza magnetica cardiaca", Corso di Laurea in Tecniche di Radiologia Medica, per Immagini e Radioterapia

*Università di Padova, Italia* \hfill Gennaio 2024

- Docente a contratto sul tema "Sicurezza in ambiente di risonanza magnetica", Master in Risonanza Magnetica Cardiaca
:::


::: {.content-visible when-profile="english"}
# Professional licenses

- Good Clinical Practice certification. *National Institute for Health and Care Research*, London, UK \hfill Oct 2022
- UK General Medical Council, reference number 8023039 \hfill Feb 2023
- "Ordine dei Medici-Chirurghi ed Odontoiatri", Chieti, Italy, medical license number 5690 \hfill May 2021
:::

::: {.content-visible when-profile="italian"}
# Licenze professionali

- Good Clinical Practice certification. *National Institute for Health and Care Research*, Londra, Regno Unito \hfill Ottobre 2022
- Abilitazione alla professione di medico-chirurgo
  - Regno Unito: General Medical Council, numero di iscrizione 8023039 \hfill Febbraio 2023
  - Italia: Ordine dei Medici-Chirurghi ed Odontoiatri di Chieti, numero di iscrizione 5690 \hfill Maggio 2021
:::

::: {.content-visible when-profile="english"}
# Professional and language skills

- Clinical research
  - systematic review and meta-analysis (5 published), diagnostic studies (accuracy, clinical utility), prognostic studies (survival analysis and modeling)
  - cost-effectiveness analysis and health technology assessment

- Data science and IT
  - Strong modelling and data visualization skills in R 
  - Dynamic, reproducible reporting in Quarto
  - Development and deployment of server-based Shiny applications
  - Experienced Git and Github user
  - Experienced REDCap user
  - Proficient in Microsoft Word, Excel, Powerpoint

- English language 
  - International English Language Testing System (IELTS) \hfill Nov 2023
    - Academic english. Listening 9.0; Reading 9.0; Speaking 8.5; Writing 7.5 (scored 1 to 10)
  - Occupational English Test (OET) \hfill Feb 2023
    - Medical english. Listening A; Reading A; Speaking B; Writing B (scored E to A) 

:::

::: {.content-visible when-profile="italian"}
# Competenze professionali e di lingua

- Ricerca clinica
  - revisione sistematica e meta-analisi (5 pubblicate), studi diagnostici (accuratezza, utilità clinica), studi prognostici (data scraping, analisi di sopravvivenza)
  - analisi di costo-efficacia e health technology assessment

- Data science e competenze informatiche
  - Competenze avanzate di visualizzazione dati e modelling in R
  - Reporting dinamico, riproducibile in Quarto
  - Sviluppo di applicazioni Shiny
  - Utente esperto di Git e Github
  - Utente esperto di REDCap
  - Utente esperto di Word, Excel, Powerpoint

- Lingua inglese
  - International English Language Testing System (IELTS) \hfill Novembre 2023
    - Inglese accademico. Listening 9.0; Reading 9.0; Speaking 8.5; Writing 7.5 (scored 1 to 10)
  - Occupational English Test (OET) \hfill Febbraio 2023
    - Inglese medico. Listening A; Reading A; Speaking B; Writing B (scored E to A) 
:::


::: {.content-visible when-profile="english"}
# Grants, prizes and awards
- Finalist, Early career award (clinical track), CMR 2024, London, UK \hfill January 2024
- Participant to research unit, ULTRALIGHT-HCM study, Italian Ministry of Public Education (€ 299,604) \hfill July 2023
- Early Career Investigator Travel Grant, AHA Scientific Sessions, Philadelphia, USA \hfill November 2023
- Educational Grant, EACVI Conference, Barcelona, Spain \hfill May 2023
- Travel Grant, SCMR Conference, San Diego, USA \hfill January 2023
- «Path of Excellence» award in Medicine, University of Chieti and Pescara, Italy \hfill October 2019
:::

::: {.content-visible when-profile="italian"}
# Grant, premi e riconoscimenti

- Finalista, Early career award (clinical track), CMR 2024, Londra, Regno Unito \hfill Gennaio 2024
- Partecipante ad unità di ricerca, studio ULTRALIGHT-HCM finanziato PRIN PNRR (€ 299.604) \hfill Luglio 2023
- Early Career Investigator Travel Grant, AHA Scientific Sessions, Philadelphia, USA \hfill Novembre 2023
- Educational Grant, EACVI Conference, Barcelona, Spain \hfill Maggio 2023
- Travel Grant, SCMR Conference, San Diego, USA \hfill Gennaio 2023
- Riconoscimento «Percorso di Eccellenza» in Medicina e Chirurgia, Università G. d’Annunzio di Chieti e Pescara, Chieti, Italia \hfill Ottobre 2019
:::

::: {.content-visible when-profile="english"}

# Certifications, affiliations, and publications

For a list of my certifications, professional affiliations, conference presentations and scientific publications, please refer to my CV supplement.
:::
::: {.content-visible when-profile="italian"}

# Certificazioni, affiliazioni e pubblicazioni scientifiche

Per una lista delle mie certificazioni, affiliazioni professionali, presentazioni a congressi e pubblicazioni scientifiche si faccia riferimento al mio CV supplement.
:::

::: {.content-visible when-profile="english"}
# Participation in certified courses, workshops, and hackathons

- Stress CMR: A Hands-On Workshop, SCMR, ACC Heart House, Washington D.C., USA \hfill 4-5 October 2024
- HFA Clinical Trials in Heart Failure Course, Naples, Italy \hfill 20-22 September 2024
- R in HTA Hackathon, Queen’s University Belfast, UK \hfill 5-6 August 2024
- R for trial and model-based cost-effectiveness analysis workshop, ScHARR, University of Sheffield, UK \hfill 28 June 2024
- Productive R Workflow course, online certification \hfill April 2024
- Clinical CMR Course (3 months, full-time), Royal Brompton Hospital, London, UK \hfill October-December 2022


:::

::: {.content-visible when-profile="italian"}
# Partecipazione a corsi certificati, workshop e hackathon

- Corso SCMR "Stress CMR: A Hands-On Workshop", ACC Heart House, Washington D.C., Stati Uniti \hfill 4-5 Ottobre 2024
- HFA Clinical Trials in Heart Failure Course, Napoli, Italia \hfill 20-22 Settembre 2024
- R in HTA Hackathon, Queen’s University Belfast, Regno Unito \hfill 5-6 Agosto 2024
- R for trial and model-based cost-effectiveness analysis workshop, University of Sheffield, Regno Unito \hfill 28 Giugno 2024
- Corso Productive R Workflow, online \hfill Aprile 2024
- Corso trimestrale di risonanza magnetica cardiaca (3 months, full-time), Royal Brompton Hospital, Londra, Regno Unito \hfill Ottobre-Dicembre 2022


:::

::: {.content-visible when-profile="english"}
# Professional affiliations

- Member of the 
  - American Heart Association \hfill 2023-present
  - American College of Cardiology (Fellow in Training) \hfill 2022-present
  - Society for Cardiovascular Magnetic Resonance (Early Career working group) \hfill 2022-present
  - European Society of Cardiology (Professional member) \hfill 2021-present
  - European Association of Cardiovascular Imaging \hfill 2021-present
  - Italian Society of Cardiology (CMR, Sex differences working groups) \hfill 2021-present

- Other affiliations
  - NHS-R Community \hfill 2024-present
  - IMSOGB - Italian Medical Society of Great Britain \hfill 2024-present
:::

::: {.content-visible when-profile="italian"}
# Affiliazioni

- Membro delle seguenti associazioni e società scientifiche:
  - American Heart Association \hfill 2023-presente 
  - American College of Cardiology (Fellow in Training) \hfill 2022-presente
  - Society for Cardiovascular Magnetic Resonance (Early Career working group) \hfill 2022-presente
  - European Society of Cardiology (Professional member) \hfill2021-presente
  - European Association of Cardiovascular Imaging \hfill 2021-presente 
  - Società Italiana di Cardiologia (CMR, Sex differences WG) \hfill 2021-presente

- Altre affiliazioni:
  - NHS-R Community \hfill 2024-presente
  - IMSOGB - Italian Medical Society of Great Britain \hfill 2024-presente
:::

# Peer Reviews
::: {.content-visible when-profile="english"}
I did peer reviews for the following journals in the last 5 years:
:::
::: {.content-visible when-profile="italian"}
Attività di revisione paritaria per le seguenti riviste indicizzate:
:::
- European Heart Journal
- Open Heart
- Journal of Clinical Medicine
- Frontiers in Public Health
- Children

::: {.content-visible when-profile="english"}
# Scientific publications
:::

::: {.content-visible when-profile="italian"}
# Pubblicazioni scientifiche
:::

```{r}
#| echo: false
#| error: false
#| warning: false
#| output: false
library(bib2df)
pubs <- length(bib2df("bibs/cv.bib")$BIBTEXKEY)
```

::: {.content-visible when-profile="english"}
I have authored `r pubs` scientific publications, where I contributed to literature review, statistical analyses, manuscript drafting, and/or preparation of visual illustrations and figures. My publications may also be accessed on [NCBI](https://www.ncbi.nlm.nih.gov/myncbi/giandomenico.bisaccia.1/bibliography/public/).

## Original research
:::

::: {.content-visible when-profile="italian"}
Ho contribuito a `r pubs` pubblicazioni scientifiche effettuando revisioni della letteratura, analisi statistiche, la prima stesura del testo, e la preparazione di illustrazioni e figure. La lista delle mie pubblicazioni è disponibile online su [NCBI](https://www.ncbi.nlm.nih.gov/myncbi/giandomenico.bisaccia.1/bibliography/public/).

## Studi originali
:::
**Safety and feasibility of adenosine stress cardiac MRI in heart transplant recipients** (2024).
**G. Bisaccia**, R. Licordari, I. Leo, G. La Vecchia, M. Perotto, M. C. Procopio, N. Miaris, F. Ricci, S. Gallina, J. Wong, P. Kellman and C. Bucciarelli-Ducci.
*European Heart Journal - Cardiovascular Imaging*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1093/ehjci/jeae174)

**Atrial electro-functional predictors of incident atrial fibrillation in cardiac amyloidosis** (2024).
G. Sinigiani, L. De Michieli, A. Porcari, C. Zocchi, A. Sorella, C. Mazzoni, **G. Bisaccia**, A. De Luca, G. Di Bella, D. Gregori, F. Perfetto, M. Merlo, G. Sinagra, S. Iliceto, M. Perazzolo Marra, D. Corrado, F. Ricci, F. Cappelli and A. Cipriani.
*Heart Rhythm*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1016/j.hrthm.2024.01.056)

**Guillain–Barré syndrome and COVID-19 vaccination: a systematic review and meta-analysis** (2024).
S. Censi, **G. Bisaccia**, S. Gallina, V. Tomassini and A. Uncini.
*Journal of Neurology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1007/s00415-024-12186-7)

**Cardiovascular Magnetic Resonance in Patients with Cardiac Electronic Devices: Evidence from a Multicenter Study** (2023).
A. Barison, F. Ricci, A. G. Pavon, G. Muscogiuri, **G. Bisaccia**, G. Camastra, M. De Lazzari, C. Lanzillo, M. Raguso, L. Monti, S. Vargiu, P. Pedrotti, M. Piacenti, G. Todiere, G. Pontone, C. Indolfi, S. Dellegrottaglie, M. Lombardi, J. Schwitter, G. D. Aquaro,
*Heart*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1136/heartjnl-2023-322835)

**Diagnostic and Prognostic Value of Stress Cardiovascular Magnetic Resonance Imaging in Patients With Known or Suspected Coronary Artery Disease: A Systematic Review and Meta-analysis** (2023).
F. Ricci, M. Y. Khanji, **G. Bisaccia**, A. Cipriani, A. Di Cesare, L. Ceriello, C. Mantini, M. Zimarino, A. Fedorowski, S. Gallina, S. E. Petersen and C. Bucciarelli-Ducci.
*JAMA Cardiology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1001/jamacardio.2023.1290)

**Prognostic Significance of Late Gadolinium Enhancement in Fabry Disease-A Systematic Review and Meta-Analysis** (2023).
F. Ricci, **G. Bisaccia**, D. Mansour, L. V. Molinari, M. Di Mauro, G. Renda, M. Y. Khanji and S. Gallina.
*The American Journal of Cardiology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1016/j.amjcard.2023.06.059)

**CMR Reclassifies the Majority of Patients with Suspected MINOCA and non MINOCA** (2023).
K. Liang, **G. Bisaccia**, I. Leo, M. G. L. Williams, A. Dastidar, J. W. Strange, E. Sammut, T. W. Johnson and C. Bucciarelli-Ducci.
*European Heart Journal - Cardiovascular Imaging*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1093/ehjci/jead182)

**Guillain-Barre syndrome and SARS-CoV-2 infection: a systematic review and meta-analysis on a debated issue and evidence for the 'Italian factor'** (2023).
S. Censi, **G. Bisaccia**, S. Gallina, V. Tomassini and A. Uncini.
*European Journal of Neurology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1111/ene.16094)

**Cardiovascular Morbidity and Mortality Related to Non-alcoholic Fatty Liver Disease: A Systematic Review and Meta-analysis** (2023).
**G. Bisaccia**, F. Ricci, M. Y. Khanji, A. Sorella, E. Melchiorre, G. Iannetti, K. Galanti, C. Mantini, A. D. Pizzi, C. Tana, G. Renda, A. Fedorowski, R. De Caterina and S. Gallina.
*Current Problems in Cardiology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1016/j.cpcardiol.2023.101643)

**Cardiovascular magnetic resonance reference values of mitral and tricuspid annular dimensions: the UK Biobank cohort** (2021).
F. Ricci, N. Aung, S. Gallina, F. Zemrak, K. Fung, **G. Bisaccia**, J. M. Paiva, M. Y. Khanji, C. Mantini and S. Palermi.
*Journal of Cardiovascular Magnetic Resonance*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1186/s12968-020-00688-y)

::: {.content-visible when-profile="english"}
## Reviews
:::
::: {.content-visible when-profile="italian"}
## Revisioni della letteratura
:::

**Cardiac Magnetic Resonance Imaging: A Utility in Heart Failure** (2024).
**G. Bisaccia** and C. Bucciarelli-Ducci.
*Heart Failure Journal of India*.
[{{< bi box-arrow-up-right >}}](https://journals.lww.com/hfji/fulltext/2024/05000/cardiac_magnetic_resonance_imaging__a_utility_in.8.aspx)


**Prevention of cardiotoxicity in childhood cancer survivors: in physical exercise, we trust** (2024).
V. Bucciarelli, F. Bianco, **G. Bisaccia**, K. Galanti, A. Arata, M. Ricci, B. Bucciarelli, M. Marinelli, G. Renda, A. Farinetti, A. V. Mattioli and S. Gallina.
*Current Problems in Cardiology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1016/j.cpcardiol.2024.102722)


**Moderate aortic stenosis: Navigating the uncharted** (2024).
M. V. Caprio, F. De Donno, **G. Bisaccia**, C. Mantini, A. Di Baldassarre, S. Gallina, M. Y. Khanji and F. Ricci.
*Echocardiography*.
[{{< bi box-arrow-up-right >}}](https://doi.org/https://doi.org/10.1111/echo.15859)


**Underlying mechanisms and cardioprotective effects of SGLT2i and GLP-1Ra: insights from cardiovascular magnetic resonance** (2024).
A. Cersosimo, N. Salerno, J. Sabatino, A. Scatteia, **G. Bisaccia**, S. De Rosa, S. Dellegrottaglie, C. Bucciarelli-Ducci, D. Torella and I. Leo.
*Cardiovascular Diabetology*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1186/s12933-024-02181-7)

**The Role of Multimodality Imaging in Pediatric Cardiomyopathies** (2023).
S. Moscatelli, I. Leo, F. Bianco, N. Borrelli, M. Beltrami, M. Garofalo, E. G. Milano, **G. Bisaccia**, F. Iellamo, P. P. Bassareo, A. Pradhan, A. Cimini and M. A. Perrone.
*Journal of Clinical Medicine*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/jcm12144866)

**The Role of Advanced Cardiovascular Imaging Modalities in Cardio-Oncology: From Early Detection to Unravelling Mechanisms of Cardiotoxicity** (2023).
I. Leo, M. Vidula, **G. Bisaccia**, M. C. Procopio, R. Licordari, M. Perotto, G. La Vecchia, N. Miaris, P. E. Bravo and C. Bucciarelli-Ducci.
*Journal of Clinical Medicine*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/jcm12154945)

**Imaging patients with myocardial infarction with non-obstructive coronary arteries (MINOCA)** (2023).
I. Leo, **G. Bisaccia**, N. Miaris, M. C. Procopio, R. Licordari and C. Bucciarelli-Ducci.
*Heart*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1136/heartjnl-2023-322835)

**Prognostic Value of High-Sensitivity Cardiac Troponin in Women** (2022).
**G. Bisaccia**, F. Ricci, M. Y. Khanji, G. Gaggi, A. Di Credico, S. Gallina, A. Di Baldassarre and B. Ghinassi.
*Biomolecules*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/biom12101496)

**Post-Acute Sequelae of COVID-19 and Cardiovascular Autonomic Dysfunction: What Do We Know?** (2021).
**G. Bisaccia**, F. Ricci, V. Recce, A. Serio, G. Iannetti, A. A. Chahal, M. Stahlberg, M. Y. Khanji, A. Fedorowski and S. Gallina.
*Journal of Cardiovascular Development and Disease*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/jcdd8110156)

**Mitochondrial Dysfunction and Heart Disease: Critical Appraisal of an Overlooked Association** (2021).
**G. Bisaccia**, F. Ricci, S. Gallina, A. Di Baldassarre and B. Ghinassi.
*International Journal of Molecular Sciences*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.3390/ijms22020614)

**Nonalcoholic fatty liver disease and cardiovascular disease phenotypes** (2020).
**G. Bisaccia**, F. Ricci, C. Mantini, C. Tana, G. L. Romani, C. Schiavone and S. Gallina.
*SAGE Open Medicine*.
[{{< bi box-arrow-up-right >}}](https://doi.org/10.1177/2050312120933804)


::: {.content-visible when-profile="english"}
# Conference presentations
:::

::: {.content-visible when-profile="italian"}
# Presentazioni a congressi internazionali
:::

## European Society of Cardiology

*Non-invasive imaging to guide percutaneous coronary revascularization in chronic total occlusion: a systematic review and meta-analysis*.
**G. Bisaccia**, J. Greenwood, C. Berry, GP. Mccann, J. Wong, F. Ricci, S. Gallina, L. Liu, Y. Wang, J. Hill, N. Curzen, C. Bucciarelli-Ducci. [Presented at ESC Congress, London, UK (August 2024)]{.content-visible when-profile="english"} [Presentato a ESC Congress, Londra, Regno Unito (Agosto 2024)]{.content-visible when-profile="italian"}

*Prognostic yield of stress CMR to evaluate chronic coronary syndromes: a systematic review and meta-analysis*.
**G. Bisaccia**, M. Khanji, S. Gallina, S. Petersen, C. Bucciarelli-Ducci and F. Ricci. [Presented at ESC Congress, Barcelona, Spain (August 2022)]{.content-visible when-profile="english"} [Presentato a ESC Congress, Barcellona, Spagna (Agosto 2022)]{.content-visible when-profile="italian"}

*Diagnostic accuracy of stress CMR to evaluate chronic coronary syndromes: an updated meta-analysis*.
**G. Bisaccia**, M. Khanji, S. Gallina, S. Petersen, C. Bucciarelli-Ducci and F. Ricci. [Presented at ESC Congress, Barcelona, Spain (August 2022)]{.content-visible when-profile="english"} [Presentato a ESC Congress, Barcellona, Spagna (Agosto 2022)]{.content-visible when-profile="italian"}

*Cardiovascular morbidity and mortality related to non-alcoholic fatty liver disease: a systematic review and meta-analysis of prospective studies*.
**G. Bisaccia**, F. Ricci, E. Melchiorre, C. Tana, G. Renda, M. Khanji, A. Fedorowski, R. De Caterina and S. Gallina. [Presented at ESC Congress (The Digital Experience) (August 2021)]{.content-visible when-profile="english"} [Presentato a ESC Congress (The Digital Experience) (Agosto 2021)]{.content-visible when-profile="italian"}

## American Heart Association

*Comparative and Incremental Diagnostic and Prognostic Yield of Exercise ECG, CMR and SPECT in Patients With Suspected Ischaemic Heart Disease: A CE-MARC Sub-Study*.
**G. Bisaccia**, P. P. Swoboda, C. Bucciarelli-Ducci, S. Plein and J. Greenwood. [Presented at AHA Scientific Sessions, Philadelphia, USA (Nov 2023)]{.content-visible when-profile="english"} [Presentato a AHA Scientific Sessions, Philadelphia, USA (Novembre 2023)]{.content-visible when-profile="italian"}

## Society for Cardiovascular Magnetic Resonance 

*Prognostic Value of Myocardial Blood Flow Index Among Heart Transplant Recipients*.
**G. Bisaccia**, R. Licordari, I. Leo, G. La Vecchia, M. Perotto, M. C. Procopio, F. Ricci, S. Gallina, J. Wong and C. Bucciarelli-Ducci. [Presented at CMR 2024, London, UK (Jan 2024).]{.content-visible when-profile="english"} [Presentato a CMR 2024 (Gennaio 2024).]{.content-visible when-profile="italian"}

*Safety and Feasibility of Adenosine Stress CMR for CAV Detection in Orthotopic Heart Transplant Recipients*.
**G. Bisaccia**, R. Licordari, I. Leo, G. La Vecchia, M. Perotto, M. C. Procopio, F. Ricci, S. Gallina, J. Wong and C. Bucciarelli-Ducci. [Presented at CMR 2024 London, UK (Jan 2024).]{.content-visible when-profile="english"} [Presentato a CMR 2024 (Gennaio 2024).]{.content-visible when-profile="italian"}

**Diagnostic and Prognostic Value of Stress CMR Imaging to Evaluate Stable Chest Pain: A Twenty-Year Meta-Analysis**. **G. Bisaccia**, F. Ricci, M. Y. Khanji, S. Gallina, S. E. Petersen, C. Bucciarelli-Ducci. [Presented at SCMR 2023 San Diego, US (Jan 2023).]{.content-visible when-profile="english"} [Presentato a SCMR 2023 San Diego, Stati Uniti (Gennaio 2023).]{.content-visible when-profile="italian"}

## European Association of Cardiovascular Imaging

*CMR reclassifies patients with suspected myocardial infarction with non-obstructive coronary arteries (MINOCA)*.
**G. Bisaccia**, K. Liang, M. G. L. Williams, I. Leo, A. Dastidar, E. Sammut, T. Johnson and C. Bucciarelli-Ducci. [Presented at EACVI, Barcelona, Spain (May 2023)]{.content-visible when-profile="english"} [Presentato a EACVI, Barcellona, Spagna (Maggio 2023)]{.content-visible when-profile="italian"}